backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "المنتجات"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "اسم المنتج", name: "title", widget: "string" }
      - label: "الفئة"
        name: "category"
        widget: "select"
        options:
          - "أجهزة تنفس"
          - "أجهزة ضغط"
          - "أجهزة قياس"
          - "تجهيز عيادات"
          - "سماعات"
          - "إسعافات أولية"
          - "أثاث طبي"
          - "مستهلكات"
          - "تجهيز معامل"
      - { label: "صورة المنتج", name: "image", widget: "image" }
      - { label: "السعر (جنيه)", name: "price", widget: "number" }
      - { label: "السعر القديم (0 إن لم يكن هناك خصم)", name: "oldPrice", widget: "number", default: 0 }
      - label: "الحالة"
        name: "status"
        widget: "select"
        options:
          - "جديد"
          - "مستعمل"
          - "إيجار"
     - label: "شارة"
        name: "badge"
        widget: "select"
        default: ""
        required: false
        options:
          - { label: "بدون شارة", value: "none" }
          - { label: "جديد", value: "new" }
          - { label: "خصم", value: "discount" }
      - { label: "نسبة الخصم % (0 إن لم يكن هناك خصم)", name: "discount", widget: "number", default: 0 }
      - { label: "وصف المنتج", name: "description", widget: "text" }
